site_name: Pytest Embrace
repo_url: https://github.com/ainsleymcgrath/pytest-embrace
theme:
  name: material
  custom_dir: docs_overrides
  palette:
    primary: white
    accent: green
  logo: logo-alt.svg
  favicon: logo-alt-alt.svg
  features:
    - content.code.annotate
    - announce.dismiss
nav:
  - index.md
  - Migrating from 2.x to 3.x: two-to-three.md
  - The Module-Test Formalism: semantics.md
  - Usage Guide:
    - usage/index.md
    - Designing Tests:
      - usage/designing-tests/index.md
      - usage/designing-tests/making-cases.md
    - Enhancing Tests:
      - usage/tables-and-modules/index.md
      - usage/leveraging-filenames/index.md
    - Code Generation:
      - usage/code-generation/index.md
  - Reference:
    - API Reference: reference/api.md
    - CLI Reference: reference/cli.md
  - about.md
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- attr_list
- md_in_html
- admonition
