site_name: Pytest Embrace
repo_url: https://github.com/ainsleymcgrath/pytest-embrace
theme:
  name: material
  palette:
    primary: white
    accent: green
  logo: logo-alt.svg
  favicon: logo-alt-alt.svg
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- attr_list
- md_in_html
