on: push

jobs:
  QA:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        # cache: poetry
      # run: poetry --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox

  Release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python for release
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
    - name: 'Pypi Release'
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install python-semantic-release
        git config user.name github-actions
        git config user.email github-actions@github.com
        semantic-release publish

  # Release:
  #   needs: Quality
  #   # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'chore(release):')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Semantic Release
  #       run: |
  #         pip install python-semantic-release
  #         git config user.name github-actions
  #         git config user.email github-actions@github.com
  #         semantic-release publish
