name: CI
on: push

jobs:
  QA:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry
    - name: Install dependencies
      run: poetry install
    - name: Test with tox
      run: poetry run tox

  Release:
    needs: QA
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: PyPi Test
    env:
      REPOSITORY_USERNAME: __token__
      REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.REPOSITORY_PASSWORD }}

  Docs:
    needs: Release
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: .python-version
    - run: pip install mkdocs-material
    - run: mkdocs gh-deploy --force
